version: '3.8'

services:
  live-docs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Exclude node_modules from mounting
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      # Add your development environment variables here
      # - NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY=your_liveblocks_key
      # - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=your_clerk_key
      # - CLERK_SECRET_KEY=your_clerk_secret
      # - CONVEX_DEPLOY_KEY=your_convex_key
    stdin_open: true
    tty: true 