version: '3.8'

services:
  live-docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Add your environment variables here
      # - NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY=your_liveblocks_key
      # - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=your_clerk_key
      # - CLERK_SECRET_KEY=your_clerk_secret
      # - CONVEX_DEPLOY_KEY=your_convex_key
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 